config/routes.rb
Rails.application.routes.draw do
  root  'static#home'

  get  'contact' => 'static#contact'
    
  get 'about' => 'static#about'

  get 'gallery' => 'static#gallery'
    
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def contact
  end

  def home
  end

  def about
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Bob's Carvin"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
  <nav>
    <ul>
      <!--<li><%= link_to "About",   about_path %></li>-->
      <!--<li><%= link_to "Contact", '#' %></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container"> 
    <nav>
       <!-- <%= link_to "Bob's Carvin", root_path, id: "logo" %>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Gallery", gallery_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>